### ISSUE TITLE
No Corpsephase

### ISSUE THREAD

**Issue by JustZerooo** [AscEmu/AscEmu_TBC#17]
Upon Kill an Unit (NPC or PC) it dies (woooooooooow) but after few sec it should become unclickable and visual for dead corpse like open mouth etc. (Thats TBC Originally) They just Die and Respawn.. No Corpsephase

**Comment by Zyres** [comment]
Not reproduceable:
![screenshot004](http://i.imgur.com/fXrLCPE.jpg)

Please give us more information (creature ids) where this problem appears for you.
