### ISSUE TITLE
Stance Bug

### ISSUE THREAD

**Issue by JustZerooo** [AscEmu/AscEmu_TBC#20]
If you use on warrior the Battle Shout Spell -> http://db.lastwow.com/?spell=6673 or other like thjis on any class or race, you will get out of your stance and yopur action bar is empty...

**Comment by ghost** [comment]
https://streamable.com/iaf8 I cannot seem to reproduce the bug

**Comment by Zyres** [comment]
Thank you @Blumfield for testing this issue.
I can not reproduce it either.
