### ISSUE TITLE
Duell not Avaible

### ISSUE THREAD

**Issue by JustZerooo** [AscEmu/AscEmu_TBC#23]
If you start a duell the server will crash and gives follow notice back:

WORLD: got cast spell packet, spellId - 7266 (Duel), data length = 11
Segmentation fault (core dumped)

Linux Ubuntu x64 / x32

**Comment by Zyres** [comment]
![not_rep](http://i.imgur.com/RrYCSRn.jpg)

Can you give us more information? This looks fine for me...

**Comment by JustZerooo** [comment]
Idk more informations ... i use Linux and if i start a duell server crashing imidently !

**Comment by Zyres** [comment]
No information about the map?
Which class/race?
Or any tip how I can reproduce it?
Not everything is related to architecture or environment so give us more information about it.

**Comment by JustZerooo** [comment]
Map is Hyjal, Class is Dreanei versus Gnome Warrior versus warlock!

i am as admin he is same as admin we start duell server crashed.

**Comment by JustZerooo** [comment]
i think it is expecting a certain data size for either the packet or the spell id.

Aug 28, 2013 - #0 0x00007f76cfb4a11d in nanosleep () from /lib/libpthread.so.0 .... 16:26:19 WORLD: Time Lag/Synchronization Resent/Update, data = .... 16:26:19 WORLD: got cast spell packet, spellId - 31884, cast_count: ... gs 0, data length = 10 ..... 16:26:20 PLAYER (Class: 11 Race: 6): Adding initial spell, id = 7266.

Posted by treetree : http://www.ac-web.org/forums/showthread.php?215974-Arcemu-Ascemu-Server-Crash-on-Duell&p=2190138&viewfull=1#post2190138
