### ISSUE TITLE
Hellfire Ramparts spawns

### ISSUE THREAD

**Issue by ghost** [AscEmu/AscEmu_TBC#28]
This instance needs a complete respawn, all the spawns are wrong it may be wrong on wotlk branch also.

instance/map id: 543

**Comment by JustZerooo** [comment]
That is what i do not have been testet :) We can check old archives for spawnpoints ?

**Comment by ghost** [comment]
Yeah I will look around and see what I can find.

**Comment by ghost** [comment]
Couldn't find anything in archives and we don't have a sniffer so i'm going to the next best thing and going to port the spawns for this instance over from oregoncore.
