### ISSUE TITLE
Quest - The Shrine of Dath'Remar

### ISSUE THREAD

**Issue by ghost** [AscEmu/AscEmu_TBC#32]
http://www.wowhead.com/quest=8345/the-shrine-of-dathremar

What it should do:

You should accept the quest from the NPC and go to the Shrine then right click and receive the text from the Shrine and it will update the quest for completion.

What it currently does:

When you run up and right click it provides the text but doesn't complete the quest.

This works on the Ascemu WOTLK branch so we might need to port what they did with the page IDs / Goober stuff if you look at the code.

**Comment by ghost** [comment]
As a heads up this isn't just a DB issue, if you set the flag to be Goober then it updates the quest but doesn't give you the text anymore.

**Comment by Cronicman** [comment]
Would like some feedback @S7urp33 when you can.

**Comment by ghost** [comment]
So it appears that I have to change it to a goober for it to complete, versus completing as a text gameobject where it actually has text etc as it does on retail.

**Comment by ghost** [comment]
So you have to change the object to a goober in the DB before it will complete when you click on it? So without that changed it won't complete? If it works with it changed to a goober i'll do a DB update commit then, but will need some more info.
